<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Monitoreo\Module'                      => __DIR__ . '/Module.php',
    'Monitoreo\Controller\IndexController'  => __DIR__ . '/src/Monitoreo/Controller/IndexController.php',
    'Monitoreo\Framework\TestCase'          => __DIR__ . '/tests/Monitoreo/Framework/TestCase.php',
    'Monitoreo\SampleTest'                  => __DIR__ . '/tests/Monitoreo/SampleTest.php',
);