<?php
// module/Album/view/album/album/index.phtml:
//var_dump($this->albums);exit;
$title = 'Personal';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('administrator/default', array('controller'=>'personal', 'action'=>'add'));?>">Nuevo personal</a>
</p>

<table class="table table-bordered table-striped">
<tr>
    <th>Nombre</th>
    <th>Perfil</th>
    <th>Departamento</th>
    <th>Cargo</th>
    <th>Fecha Alta</th>
    <th>Acción</th>
</tr>
<?php foreach ($this->paginator as $row) : ?>
<tr>
    <td><?php echo $this->escapeHtml($row->nombre) . ' ' . $this->escapeHtml($row->a_paterno);?></td>
    <td><?php echo $this->escapeHtml($row->id_rol);?></td>
    <td><?php echo $this->escapeHtml($row->departamento);?></td>
    <td><?php echo $this->escapeHtml($row->cargo);?></td>
    <td><?php echo $this->escapeHtml($row->getFechaAlta('d/m/Y'));?></td>
    <td>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'personal', 'action'=>'edit', 'id' => $row->id_personal));?>">Edit</a>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'personal', 'action'=>'delete', 'id' => $row->id_personal));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php
echo $this->paginationControl(
            $paginator, 'Sliding', 'paginator-slide', array('order_by' => $order_by, 'order' => $order, 'controller' => 'personal')
    );
    ?>
