<script type="text/javascript">
var urlform = '<?php echo $this->url('application/default', array('controller'=>'settings', 'action'=>'verificapass')); ?>';
</script>
<?php echo $this->headScript()->appendFile($this->basePath() . '/js/valida.password.js'); ?>
<?php
// module/Application/view/application/setting/password.phtml:
$title = 'Cambiar contraseña';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller' => 'settings', 'action' => 'password')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<fielset>
    <legend><?php echo $this->escapeHtml($title); ?></legend>
<?
//Nombre de usuario
if(isset($this->msg_error)){
    echo $this->msg_error;
}
?><div class="control-group"><?
echo $this->formLabel($form->get('current_password'));
?><div class="controls"><?
echo $this->formPassword($form->get('current_password'));
echo $this->formElementErrors($form->get('current_password'));
?>
    <span id="mimensaje" class="help-inline"></span>
    <div  ></div></div><?
?></div><?
//Password
?><div class="control-group"><?
echo $this->formLabel($form->get('password'));
?><div class="controls"><?
echo $this->formPassword($form->get('password'));
echo $this->formElementErrors($form->get('password'));
?>
    <span class="meter help-inline"></span>
<!--<div class="strength-indicator">
   <div class="meter">
   </div>
   Strong passwords contain 8-16 characters.
</div>-->
</div><?
?></div><?

//Password
?><div class="control-group"><?
echo $this->formLabel($form->get('password_confirmation'));
?><div class="controls"><?
echo $this->formPassword($form->get('password_confirmation'));
echo $this->formElementErrors($form->get('password_confirmation'));
?>
<span id="label_confirm" class="help-inline"></span>
</div><?
?></div><?

echo $this->formSubmit($form->get('submit'));
?>
</fielset>
<?
echo $this->form()->closeTag();
?>