<strong>User:</strong>        <?php echo $this->user; ?>
<p><a href="<?php echo $this->url('application/default', array('controller'=>'account', 'action'=>'logout'));?>">Cerrar sesión</a></p>
<?php
// module/Album/view/album/album/index.phtml:
//var_dump($this->albums);exit;
$title = 'Roles / Perfiles';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('administrator/default', array('controller'=>'roles', 'action'=>'add'));?>">Add new personal</a>
</p>

<table class="table table-bordered table-striped">
<tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Acción</th>
</tr>
<?php foreach ($this->rol as $row) : ?>
<tr>
    <td><?php echo $this->escapeHtml($row->nombre);?></td>
    <td><?php echo $this->escapeHtml($row->descripcion);?></td>
    <td>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'roles', 'action'=>'edit', 'id' => $row->id_rol));?>">Edit</a>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'roles', 'action'=>'delete', 'id' => $row->id_rol));?>">Delete</a>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'roles', 'action'=>'permisos', 'id' => $row->id_rol));?>">Permisos</a>
    </td>
</tr>
<?php endforeach; ?>
</table>