<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Contact Center'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style_pschecker.css')
                        ->prependStylesheet($this->basePath() . '/jquery_ui/css/redmond/jquery-ui-1.10.3.custom.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/jquery_ui/ui/i18n/jquery.ui.datepicker-es.js')
                                      ->prependFile($this->basePath() . '/jquery_ui/ui/jquery-ui.custom.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                       ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Contact Center'); ?></a>
                    
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Home'); ?></a></li>
                            <li><a href="<?php echo $this->url('administrator/default', array('controller' => 'users')); ?>"><?php echo $this->translate('Users'); ?></a></li>
                            <li><a href="<?php echo $this->url('administrator/default', array('controller' => 'personal')); ?>"><?php echo $this->translate('Personal'); ?></a></li>
                            <li><a href="<?php echo $this->url('administrator/default', array('controller' => 'campanas')); ?>"><?php echo $this->translate('Campanas'); ?></a></li>
                            <li><a href="<?php echo $this->url('reportes/default', array('controller' => 'index')); ?>"><?php echo $this->translate('Reportes'); ?></a></li>
                        </ul>
                        <ul class="nav pull-right">
                            <li>
                                <a href="#"><?php echo $this->layout()->nickname; ?></a>
                            </li>
                            <li class="divider-vertical"></li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Config
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="<?php echo $this->url('application/default', array('controller' => 'settings', 'action' => 'password')); ?>">Cambiar contraseña</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->url('application/default', array('controller' => 'account', 'action' => 'logout')); ?>">Salir</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
                <div class="nav-collapse">
                    <?php echo $this->navigation('navigation')
                            ->menu()
                            ->setMinDepth(0)
                            ->setMaxDepth(0)
                            ->setUlClass('nav')
                            ->render(); ?>
                </div>
                <li>
                    <a href="#overview">
                        <i class="icon-chevron-right"></i>
                        Overview
                    </a>
                </li>
                <?php //echo $this->layout()->sidebar; ?>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        
        <div class="span9">
          <div class="row-fluid">
              <div class="mini-layout">
              <?php echo $this->layout()->content; ?>
              </div>
          </div><!--/row-->
        
        </div><!--/span-->
      </div><!--/row-->

      <hr>

<!--      <footer>
        <p>&copy; Company 2013</p>
      </footer>-->

    </div>
            <footer>
                <p>&copy; 2012 - <?php echo date('Y') ?> by Itsa Interactive. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
