<?php
$title = 'Reportes';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('reportes/default', array('controller'=>'usuarios', 'action'=>'index'));?>">Reporte 1</a>
</p>
<p>
    <a href="<?php echo $this->url('reportes/default', array('controller'=>'index', 'action'=>'add'));?>">Reporte 2</a>
</p>
<p>
    <a href="<?php echo $this->url('reportes/default', array('controller'=>'index', 'action'=>'add'));?>">Reporte 3</a>
</p>
<p>
    <a href="<?php echo $this->url('reportes/default', array('controller'=>'index', 'action'=>'add'));?>">Reporte 4</a>
</p>
<p>
    <a href="<?php echo $this->url('reportes/default', array('controller'=>'index', 'action'=>'add'));?>">Reporte 5</a>
</p>
<p>
    <a href="<?php echo $this->url('reportes/default', array('controller'=>'index', 'action'=>'add'));?>">Reporte 6</a>
</p>

