<?php
// module/Album/view/album/album/index.phtml:
//var_dump($this->albums);exit;
$title = 'Monitoreo';
$this->headTitle($title);
?>
<div class="span5">
<h3><?php echo $this->escapeHtml('Graficas'); ?></h3>
<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('album/default',
            array('controller'=>'index', 'action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album/default',
            array('controller'=>'index', 'action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>    
</div>
<div class="span5">
<h3><?php echo $this->escapeHtml('Usuarios conectados'); ?></h3>
<table class="table table-bordered table-striped">
<tr>
    <th>Nombre</th>
    <th>Campaña</th>
    <th>Status</th>
    <th>Hora</th>
</tr>
<?php foreach ($this->albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('album/default',
            array('controller'=>'index', 'action'=>'edit', 'id' => $album->id));?>">Edit</a>
    </td>
</tr>
<?php endforeach; ?>
</table>    
</div>
