<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Administrator\Module'                      => __DIR__ . '/Module.php',
    'Administrator\Controller\IndexController'  => __DIR__ . '/src/Administrator/Controller/IndexController.php',
    'Administrator\Framework\TestCase'          => __DIR__ . '/tests/Administrator/Framework/TestCase.php',
    'Administrator\SampleTest'                  => __DIR__ . '/tests/Administrator/SampleTest.php',
);