<table class="table table-striped" id="tbl_codigos_postales">
    <thead>
        <tr>
            <th>IDENT</th>
            <th>USERNAME</th>
            <th>NOMBRE</th>
            <th>PERFIL</th>
           
        </tr>
    </thead>
    <tbody>
         <?php 
         //var_dump($this->datos);exit;
         foreach ($paginator as $row):
             //var_dump($row);exit;
             ?>
            <tr>
                <td><a class="cps" href="<?php echo $href; ?>" ><?php echo $this->escapeHtml($row['id_usuario']); ?></a></td>
                <td><?php echo $this->escapeHtml($row['username']); ?></td>
                <td><?php echo $this->escapeHtml($row['nombre'].' '.$row['a_paterno']); ?></td>
                <td><?php echo $this->escapeHtml($row['perfil']); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php
echo $this->paginationControl(
            $paginator, 'Sliding', 'paginator-report', array('order_by' => $order_by, 'order' => $order, 'controller' => 'usuarios', 'action' => 'display')
    );
    ?>