<!--<strong>User:</strong>        <?php echo $this->user; ?>
<p><a href="<?php echo $this->url('application/default', array('controller'=>'account', 'action'=>'logout'));?>">Cerrar sesión</a></p>-->
<?php
// module/Album/view/album/album/index.phtml:
//var_dump($this->albums);exit;
$title = 'Usuarios';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('administrator/default', array('controller'=>'users', 'action'=>'add'));?>">Nuevo usuario</a>
</p>

<table class="table table-bordered table-striped">
<tr>
    <th>Username</th>
    <th>Nombre</th>
    <th>Último acceso</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->users as $row) : ?>
<tr>
    <td><?php echo $this->escapeHtml($row->username);?></td>
    <td><?php echo $this->escapeHtml($row->username);?></td>
    <td><?php echo $this->escapeHtml($row->getUltimoAcceso('d-m-Y H:m'));?></td>
    <td>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'users', 'action'=>'edit', 'id' => $row->id_usuario));?>">Edit</a>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'users', 'action'=>'delete', 'id' => $row->id_usuario));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>