<strong>User:</strong>        <?php echo $this->user; ?>
<p><a href="<?php echo $this->url('application/default', array('controller'=>'account', 'action'=>'logout'));?>">Cerrar sesión</a></p>
<?php
// module/Album/view/album/album/index.phtml:
//var_dump($this->albums);exit;
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album/default', array('controller'=>'index', 'action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('album/default',
            array('controller'=>'index', 'action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album/default',
            array('controller'=>'index', 'action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>