<?php
// module/Administrator/view/administrator/recursos/add.phtml:
$title = 'Nuevo recurso';
$this->headTitle($title);
?>
<h1><?php //echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('administrator/default', array('controller' => 'recursos', 'action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<fielset>
    <legend><?php echo $this->escapeHtml($title); ?></legend>
<?
echo $this->formHidden($form->get('id_recurso'));
echo $this->formHidden($form->get('eliminado')->setValue(0));
//Id Padre
?><div class="control-group"><?
echo $this->formLabel($form->get('id_padre'));
?><div class="controls"><?
echo $this->formSelect($form->get('id_padre'));
echo $this->formElementErrors($form->get('id_padre'));
?></div><?
?></div>
<?
//Nombre
?><div class="control-group"><?
echo $this->formLabel($form->get('nombre'));
?><div class="controls"><?
echo $this->formText($form->get('nombre'));
echo $this->formElementErrors($form->get('nombre'));
?></div><?
?></div><?
//Apellido Paterno
?><div class="control-group"><?
echo $this->formLabel($form->get('descripcion'));
?><div class="controls"><?
echo $this->formText($form->get('descripcion'));
echo $this->formElementErrors($form->get('descripcion'));
?></div><?
?></div><?
echo $this->formSubmit($form->get('submit'));
?>
</fielset>
<?
echo $this->form()->closeTag();
?>