<?php
// module/Album/view/album/album/index.phtml:
//var_dump($this->albums);exit;
$title = 'Permisos del perfil: ';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<table class="table table-bordered table-striped">
<tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Acción</th>
</tr>
<?php foreach ($this->rol as $row) : ?>
<tr>
    <td><?php echo $this->escapeHtml($row->recurso);?></td>
    <td><?php echo $this->escapeHtml($row->descripcion);?></td>
    <td>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'roles', 'action'=>'edit', 'id' => $row->id_rol));?>">Edit</a>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'roles', 'action'=>'delete', 'id' => $row->id_rol));?>">Delete</a>
        <a href="<?php echo $this->url('administrator/default',
            array('controller'=>'roles', 'action'=>'permisos', 'id' => $row->id_rol));?>">Permisos</a>
    </td>
</tr>
<?php endforeach; ?>
</table>